services:
  - type: web
    name: codeleap-backend-django
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn codeleap_backend_django.wsgi"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
    plan: free